// SPDX-License-Identifier: GPL-2.0-only
// This driver is derived from Linux alx and is GPL-2.0-only.
#pragma once

#include <drivers/pci.h>
#include <stdint.h>

#define ATHEROS_VEND 0x1969
#define AR8162_DEV 0x1090

#define ATL1C_BIT(x) (1u << (x))

#define REG_MASTER_CTRL 0x1400
#define MASTER_CTRL_SOFT_RST ATL1C_BIT(0)
#define MASTER_CTRL_WAKEN_25M ATL1C_BIT(5)
#define MASTER_CTRL_OOB_DIS ATL1C_BIT(6)
#define MASTER_CTRL_SA_TIMER_EN ATL1C_BIT(7)
#define MASTER_CTRL_PCLKSEL_SRDS ATL1C_BIT(12)
#define MASTER_CTRL_TX_ITIMER_EN ATL1C_BIT(10)
#define MASTER_CTRL_RX_ITIMER_EN ATL1C_BIT(11)
#define MASTER_CTRL_INT_RDCLR ATL1C_BIT(14)

#define REG_PHY_CTRL 0x140C
#define PHY_CTRL_100AB_EN ATL1C_BIT(17)
#define PHY_CTRL_POWER_DOWN ATL1C_BIT(14)
#define PHY_CTRL_PLL_ON ATL1C_BIT(13)
#define PHY_CTRL_RST_ANALOG ATL1C_BIT(12)
#define PHY_CTRL_HIB_PULSE ATL1C_BIT(11)
#define PHY_CTRL_HIB_EN ATL1C_BIT(10)
#define PHY_CTRL_IDDQ ATL1C_BIT(7)
#define PHY_CTRL_GATE_25M ATL1C_BIT(5)
#define PHY_CTRL_LED_MODE ATL1C_BIT(2)
#define PHY_CTRL_DSPRST_OUT ATL1C_BIT(0)
#define PHY_CTRL_CLS (PHY_CTRL_LED_MODE | PHY_CTRL_100AB_EN | PHY_CTRL_PLL_ON)

#define REG_SERDES 0x1424
#define SERDES_PHYCLK_SLWDWN ATL1C_BIT(18)
#define SERDES_MACCLK_SLWDWN ATL1C_BIT(17)

#define REG_MAC_CTRL 0x1480
#define MAC_CTRL_WOLSPED_SWEN ATL1C_BIT(30)
#define MAC_CTRL_MHASH_ALG_HI5B ATL1C_BIT(29)
#define MAC_CTRL_BRD_EN ATL1C_BIT(26)
#define MAC_CTRL_SPEED_MASK 0x3u
#define MAC_CTRL_SPEED_SHIFT 20
#define MAC_CTRL_SPEED_10_100 1u
#define MAC_CTRL_PCRCE ATL1C_BIT(7)
#define MAC_CTRL_CRCE ATL1C_BIT(6)
#define MAC_CTRL_FULLD ATL1C_BIT(5)
#define MAC_CTRL_RXFC_EN ATL1C_BIT(3)
#define MAC_CTRL_TXFC_EN ATL1C_BIT(2)
#define MAC_CTRL_RX_EN ATL1C_BIT(1)
#define MAC_CTRL_TX_EN ATL1C_BIT(0)

#define REG_MAC_STA_ADDR 0x1488
#define REG_MTU 0x149C

#define REG_WOL_CTRL 0x14A0

#define REG_MDIO_CTRL 0x1414
#define MDIO_CTRL_MODE_EXT ATL1C_BIT(30)
#define MDIO_CTRL_POST_READ ATL1C_BIT(29)
#define MDIO_CTRL_AP_EN ATL1C_BIT(28)
#define MDIO_CTRL_BUSY ATL1C_BIT(27)
#define MDIO_CTRL_CLK_SEL_SHIFT 24
#define MDIO_CTRL_START ATL1C_BIT(23)
#define MDIO_CTRL_SPRES_PRMBL ATL1C_BIT(22)
#define MDIO_CTRL_OP_READ ATL1C_BIT(21)
#define MDIO_CTRL_REG_SHIFT 16
#define MDIO_CTRL_DATA_SHIFT 0

#define REG_LOAD_PTR 0x1534
#define REG_RX_BASE_ADDR_HI 0x1540
#define REG_TX_BASE_ADDR_HI 0x1544
#define REG_RFD0_HEAD_ADDR_LO 0x1550
#define REG_RRD0_HEAD_ADDR_LO 0x1568
#define REG_RFD_RING_SIZE 0x1560
#define REG_RX_BUF_SIZE 0x1564
#define REG_RRD_RING_SIZE 0x1578
#define REG_TPD_PRI0_ADDR_LO 0x1580
#define REG_TPD_RING_SIZE 0x1584
#define REG_TXQ_CTRL 0x1590
#define REG_TXQ1_CTRL 0x1594
#define REG_RXQ_CTRL 0x15A0
#define REG_RXQ2_CTRL 0x15A8
#define REG_DMA_CTRL 0x15C0
#define REG_SMB_STAT_TIMER 0x15C4
#define REG_TINT_TPD_THRSHLD 0x15C8
#define REG_TINT_TIMER 0x15CC
#define REG_MSI_MAP_TBL1 0x15D0
#define MSI_MAP_TBL1_TXQ0_SHIFT 16
#define MSI_MAP_TBL1_RXQ0_SHIFT 0
#define REG_MSI_ID_MAP 0x15D4
#define REG_MSI_MAP_TBL2 0x15D8

#define REG_UE_SVRT 0x010C
#define UE_SVRT_DLPROTERR ATL1C_BIT(4)
#define UE_SVRT_FCPROTERR ATL1C_BIT(13)

#define REG_PDLL_TRNS1 0x1104
#define PDLL_TRNS1_D3PLLOFF_EN ATL1C_BIT(11)

#define REG_PMCTRL 0x12F8
#define PMCTRL_ASPM_FCEN ATL1C_BIT(30)
#define PMCTRL_L0S_EN ATL1C_BIT(12)
#define PMCTRL_L1_EN ATL1C_BIT(3)

#define REG_MISC 0x19C0
#define MISC_INTNLOSC_OPEN ATL1C_BIT(3)
#define MISC_ISO_EN ATL1C_BIT(12)

#define REG_MISC3 0x19CC
#define MISC3_25M_BY_SW ATL1C_BIT(1)
#define MISC3_25M_NOTO_INTNL ATL1C_BIT(0)

#define REG_MSIC2 0x19C8
#define MSIC2_CALB_START ATL1C_BIT(0)
#define REG_MB_RFD0_PROD_IDX 0x15E0
#define REG_TPD_PRI0_PIDX 0x15F2
#define REG_TPD_PRI0_CIDX 0x15F6
#define REG_MB_RFD01_CONS_IDX 0x15F8

#define TXQ_CTRL_EN ATL1C_BIT(5)
#define TXQ_CTRL_ENH_MODE ATL1C_BIT(6)
#define TXQ_CTRL_LS_8023_EN ATL1C_BIT(7)
#define TXQ_CTRL_IP_OPTION_EN ATL1C_BIT(4)
#define TXQ_NUM_TPD_BURST_SHIFT 0
#define TXQ_NUM_TPD_BURST_MASK 0xFu
#define TXQ_TXF_BURST_NUM_SHIFT 16
#define L1C_TXQ_TXF_BURST_PREF 0x200u
#define TXQ_TPD_BURST_PREF_DEF 5u
#define TXQ_TXF_BURST_PREF_DEF 0x200u

#define TXQ1_ERRLGPKT_DROP_EN ATL1C_BIT(11)
#define TXQ1_JUMBO_TSO_TH (7u * 1024u)

#define RXQ_CTRL_EN ATL1C_BIT(31)
#define RXQ_RFD_BURST_NUM_SHIFT 20
#define RXQ_RFD_BURST_NUM_DEF 8u
#define RXQ_RSS_HASH_EN ATL1C_BIT(29)
#define RXQ_RSS_MODE_SHIFT 26
#define RXQ_RSS_MODE_DIS 0u
#define RXQ_IDT_TBL_SIZE_SHIFT 8
#define RXQ_IDT_TBL_SIZE_DEF 0x100u
#define RXQ_IPV6_PARSE_EN ATL1C_BIT(7)
#define RXQ_RSS_HSTYP_ALL (ATL1C_BIT(2) | ATL1C_BIT(3) | ATL1C_BIT(4) | ATL1C_BIT(5))

#define RXQ2_RXF_XOFF_THRESH_SHIFT 16
#define RXQ2_RXF_XON_THRESH_SHIFT 0

#define MTU_STD_ALGN 1536u

#define DMA_CTRL_RREQ_PRI_DATA ATL1C_BIT(10)
#define DMA_CTRL_WDLY_CNT_SHIFT 16
#define DMA_CTRL_RDLY_CNT_SHIFT 11
#define DMA_CTRL_WDLY_CNT_DEF 4u
#define DMA_CTRL_RDLY_CNT_DEF 15u
#define DMA_CTRL_RREQ_BLEN_SHIFT 4
#define DMA_CTRL_RREQ_BLEN_MASK 0x7u
#define DMA_CTRL_RORDER_MODE_SHIFT 0
#define DMA_CTRL_RORDER_MODE_OUT 4u

#define REG_ISR 0x1600
#define REG_IMR 0x1604
#define REG_INT_RETRIG_TIMER 0x1608
#define REG_IRQ_MODRT_TIMER_INIT 0x1408
#define IRQ_MODRT_TIMER_MASK 0xFFFFu
#define IRQ_MODRT_TX_TIMER_SHIFT 0
#define IRQ_MODRT_RX_TIMER_SHIFT 16

#define ISR_DIS ATL1C_BIT(31)
#define ISR_RX_Q0 ATL1C_BIT(16)
#define ISR_TX_Q0 ATL1C_BIT(15)
#define ISR_PHY ATL1C_BIT(12)
#define ISR_DMAW ATL1C_BIT(10)
#define ISR_DMAR ATL1C_BIT(9)
#define ISR_TXF_UR ATL1C_BIT(8)
#define ISR_RFD_UR ATL1C_BIT(4)
#define ISR_RXF_OV ATL1C_BIT(3)
#define ISR_MANU ATL1C_BIT(2)
#define ISR_TIMER ATL1C_BIT(1)
#define ISR_SMB ATL1C_BIT(0)

#define REG_CLK_GATE_CTRL 0x1814
#define CLK_GATE_DMAW ATL1C_BIT(0)
#define CLK_GATE_DMAR ATL1C_BIT(1)
#define CLK_GATE_TXQ ATL1C_BIT(2)
#define CLK_GATE_RXQ ATL1C_BIT(3)
#define CLK_GATE_TXMAC ATL1C_BIT(4)
#define CLK_GATE_RXMAC ATL1C_BIT(5)
#define CLK_GATE_ALL (CLK_GATE_RXMAC | CLK_GATE_TXMAC | CLK_GATE_RXQ | CLK_GATE_TXQ | CLK_GATE_DMAR | CLK_GATE_DMAW)

#define REG_MSI_RETRANS_TIMER 0x1920
#define MSI_MASK_SEL_LINE ATL1C_BIT(16)
#define MSI_RETRANS_TM_MASK 0xFFFFu
#define MSI_RETRANS_TM_SHIFT 0

struct atl1c_tpd_desc {
    uint16_t buffer_len;
    uint16_t vlan_tag;
    uint32_t word1;
    uint64_t buffer_addr;
} __attribute__((packed));

struct atl1c_rx_free_desc {
    uint64_t buffer_addr;
} __attribute__((packed));

struct atl1c_recv_ret_status {
    uint32_t word0;
    uint32_t rss_hash;
    uint16_t vlan_tag;
    uint16_t flag;
    uint32_t word3;
} __attribute__((packed));

#define TPD_EOP_SHIFT 31
#define TPD_ETHTYPE_SHIFT 17
#define RRS_RX_RFD_CNT_SHIFT 16
#define RRS_RX_RFD_CNT_MASK 0x000Fu
#define RRS_RX_RFD_INDEX_SHIFT 20
#define RRS_RX_RFD_INDEX_MASK 0x0FFFu
#define RRS_PKT_SIZE_SHIFT 0
#define RRS_PKT_SIZE_MASK 0x3FFFu
#define RRS_RXD_UPDATED ATL1C_BIT(31)

void atl1c_init(struct pci_device device);
int atl1c_send_packet(const void *data, uint16_t len);
void atl1c_receive(void);
void atl1c_get_mac(uint8_t *mac_out);
