#pragma once

#define SYS_WRITE 0
#define SYS_READ 1
#define SYS_EXECVE 2
#define SYS_EXIT 3
#define SYS_FORK 4
#define SYS_WAIT 5
#define SYS_GETPID 6
#define SYS_YIELD 7
#define SYS_SPAWN 8
#define SYS_SBRK 9
#define SYS_OPEN 10
#define SYS_CLOSE 11
#define SYS_READDIR 12
#define SYS_CHDIR 13
#define SYS_SLEEP 14
#define SYS_MKNOD 15
#define SYS_IOCTL 16
#define SYS_MMAP 17
#define SYS_MUNMAP 18
#define SYS_STAT 20
#define SYS_FSTAT 21
#define SYS_LINK 22
#define SYS_UNLINK 23
#define SYS_GETCWD 24
#define SYS_GETTIMEOFDAY 25
#define SYS_USLEEP 26
#define SYS_PIPE 27
#define SYS_LSEEK 28
#define SYS_DUP 29
#define SYS_SHUTDOWN 30
#define SYS_REBOOT 31
#define SYS_KILL 32
#define SYS_SOCKET 33
#define SYS_BIND 34
#define SYS_SENDTO 35
#define SYS_RECVFROM 36
#define SYS_LISTEN 37
#define SYS_ACCEPT 38
#define SYS_SIGACTION 39
#define SYS_SIGRETURN 40
#define SYS_THREAD_CREATE 41
#define SYS_THREAD_EXIT 42
#define SYS_THREAD_JOIN 43
#define SYS_GETTID 44
#define SYS_FUTEX_WAIT 45
#define SYS_FUTEX_WAKE 46
#define SYS_THREAD_DETACH 47
#define SYS_WAITPID 48
#define SYS_RENAME 49
#define SYS_ARCH_PRCTL 50
#define SYS_SHM_OPEN 51
#define SYS_SHM_UNLINK 52
#define SYS_DUP2 53
#define SYS_OPENPTY 54
#define SYS_FTRUNCATE 55
#define SYS_POLL 56
#define SYS_FCNTL 57
#define SYS_SIGPROCMASK 58

#define ARCH_SET_FS 0x1002
#define ARCH_GET_FS 0x1003
